import {
    Tooltip,
    TooltipContent,
    TooltipProvider,
    TooltipTrigger,
} from "@/components/ui/tooltip";

export default function Footer() {
    return (
        <TooltipProvider delayDuration={100}>
            <footer className="w-full py-4 mt-4">
                <div className="flex items-center justify-between">
                    <div className="flex items-center justify-start gap-1">
                        <a
                            className="relative px-4 py-2 rounded-lg text-sm font-medium transition-all text-neutral-600 dark:text-neutral-400 hover:text-neutral-800 dark:hover:text-neutral-200"
                            rel="noopener noreferrer"
                            target="_blank"
                            href="https://github.com/kalil0321/"
                        >
                            github
                        </a>
                        <a
                            className="relative px-4 py-2 rounded-lg text-sm font-medium transition-all text-neutral-600 dark:text-neutral-400 hover:text-neutral-800 dark:hover:text-neutral-200"
                            rel="noopener noreferrer"
                            target="_blank"
                            href="https://linkedin.com/in/kalil-sama-bouzigues"
                        >
                            linkedin
                        </a>
                        <Tooltip>
                            <TooltipTrigger asChild className="hidden sm:block">
                                <a
                                    className="group relative px-4 py-2 rounded-lg text-sm font-medium transition-all text-neutral-600 dark:text-neutral-400 hover:text-neutral-800 dark:hover:text-neutral-200 animate-float"
                                    rel="noopener noreferrer"
                                >
                                    <span className="relative z-10 transition-transform group-hover:scale-[1.02] duration-300">
                                        hello, i am not sure of anything.
                                    </span>
                                    <div className="absolute inset-0 bg-gradient-to-r from-purple-500/0 via-purple-500/5 to-purple-500/0 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity duration-500 animate-shimmer bg-[length:200%_100%]" />
                                </a>
                            </TooltipTrigger>
                            <TooltipContent
                                className="data-[state=delayed-open]:data-[side=top]:animate-slideDownAndFade 
                                         data-[state=delayed-open]:data-[side=right]:animate-slideLeftAndFade 
                                         data-[state=delayed-open]:data-[side=left]:animate-slideRightAndFade 
                                         data-[state=delayed-open]:data-[side=bottom]:animate-slideUpAndFade 
                                         select-none rounded-xl px-4 py-3 
                                         bg-white/90 dark:bg-neutral-800/90 backdrop-blur-md
                                         shadow-[0_0_20px_rgba(0,0,0,0.05)] dark:shadow-[0_0_20px_rgba(0,0,0,0.3)]
                                         border border-neutral-200/50 dark:border-neutral-700/50
                                         max-w-[300px] text-center"
                                sideOffset={8}
                            >
                                <div className="relative">
                                    <p className="text-sm text-neutral-600 dark:text-neutral-400">
                                        this sentence was generated by our 100m
                                        tinylm for mathqa model and i found it
                                        cool so here it is
                                    </p>
                                    <div className="absolute -inset-4 bg-gradient-to-r from-violet-500/0 via-violet-500/5 to-violet-500/0 animate-shimmer bg-[length:200%_100%] rounded-xl" />
                                </div>
                            </TooltipContent>
                        </Tooltip>
                    </div>

                    <span className="text-sm font-medium text-neutral-600 dark:text-neutral-400">
                        © {new Date().getFullYear()}
                    </span>
                </div>
            </footer>
        </TooltipProvider>
    );
}
